version: "3"

services: 
    db:
        image: postgres:13
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        restart: always
        volumes: 
            - pgadmindata:/var/lib/pgadmin
        environment: 
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        logging:
            driver: none

    web:
        image: ggingmin/kube-fastapi-sampleapp:1.0 
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        restart: always
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        depends_on: 
            - db

volumes: 
    pgdata:
    pgadmindata:
