apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: fastapi
  name: fastapi
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: fastapi
status:
  loadBalancer: {}
