apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: fastapi
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: fastapi
    spec:
      containers:
        - args:
            - bash
            - -c
            - alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
          image: ggingmin/kube-fastapi-sampleapp:latest
          name: fastapi
          ports:
            - containerPort: 8000
            - name: fastapi
          resources: {}
      restartPolicy: Always
status: {}
